table = [{'program': 'S2', 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': 1, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'ACC', 'integer': None, 'show': None,  # Row 1
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': 'S3', 'show': None,  # Row 2
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 3, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 3
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S9', ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 4
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 10, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R5', 'integer': None, 'show': 'R5',  # Row 5
          'a': 'R5', 'b': 'R5', 'r': 'R5', 's': 'R5', ';': 'R5', ':': 'R5', '(': None, ')': 'R5', ',': 'R5',
          '+': 'R5', '-': 'R5', '*': 'R5', '/': 'R5', '=': 'R5', '0': 'R5', '1': 'R5', '2': 'R5',
          '3': 'R5', '4': 'R5', '5': 'R5', '6': 'R5', '7': 'R5', '8': 'R5', '9': 'R5', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R6', 'integer': None, 'show': 'R6',  # Row 6
          'a': 'R6', 'b': 'R6', 'r': 'R6', 's': 'R6', ';': 'R6', ':': 'R6', '(': None, ')': 'R6', ',': 'R6',
          '+': 'R6', '-': 'R6', '*': 'R6', '/': 'R6', '=': 'R6', '0': 'R6', '1': 'R6', '2': 'R6',
          '3': 'R6', '4': 'R6', '5': 'R6', '6': 'R6', '7': 'R6', '8': 'R6', '9': 'R6', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R7', 'integer': None, 'show': 'R7',  # Row 7
          'a': 'R7', 'b': 'R7', 'r': 'R7', 's': 'R7', ';': 'R7', ':': 'R7', '(': None, ')': 'R7', ',': 'R7',
          '+': 'R7', '-': 'R7', '*': 'R7', '/': 'R7', '=': 'R7', '0': 'R7', '1': 'R7', '2': 'R7',
          '3': 'R7', '4': 'R7', '5': 'R7', '6': 'R7', '7': 'R7', '8': 'R7', '9': 'R7', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R8', 'integer': None, 'show': 'R8',  # Row 8
          'a': 'R8', 'b': 'R8', 'r': 'R8', 's': 'R8', ';': 'R8', ':': 'R8', '(': None, ')': 'R8', ',': 'R8',
          '+': 'R8', '-': 'R8', '*': 'R8', '/': 'R8', '=': 'R8', '0': 'R8', '1': 'R8', '2': 'R43',
          '3': 'R8', '4': 'R8', '5': 'R8', '6': 'R8', '7': 'R8', '8': 'R8', '9': 'R8', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': 'S23', 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 9
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R10', 'integer': None, 'show': 'R10',  # Row 10
          'a': 'R10', 'b': 'R10', 'r': 'R10', 's': 'R10', ';': 'R10', ':': 'R10', '(': None, ')': 'R10', ',': 'R10',
          '+': 'R10', '-': 'R10', '*': 'R10', '/': 'R10', '=': 'R10', '0': 'R10', '1': 'R10', '2': 'R10',
          '3': 'R10', '4': 'R10', '5': 'R10', '6': 'R10', '7': 'R10', '8': 'R10', '9': 'R10', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 11
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 24, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 12 Follow(R) : 'R50'
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': 'R50', ':': 'R50', '(': None, ')': 'R50', ',': 'R50',
          '+': 'R50', '-': 'R50', '*': 'R50', '/': 'R50', '=': 'R50', '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 25, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R33', 'integer': None, 'show': 'R33',  # Row 13
          'a': 'R33', 'b': 'R33', 'r': 'R33', 's': 'R33', ';': 'R33', ':': 'R33', '(': None, ')': 'R33', ',': 'R33',
          '+': 'R33', '-': 'R33', '*': 'R33', '/': 'R33', '=': 'R33', '0': 'R33', '1': 'R33', '2': 'R33',
          '3': 'R33', '4': 'R33', '5': 'R33', '6': 'R33', '7': 'R33', '8': 'R33', '9': 'R33', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R34', 'integer': None, 'show': 'R34',  # Row 14
          'a': 'R34', 'b': 'R34', 'r': 'R34', 's': 'R34', ';': 'R34', ':': 'R34', '(': None, ')': 'R34', ',': 'R34',
          '+': 'R34', '-': 'R34', '*': 'R34', '/': 'R34', '=': 'R34', '0': 'R34', '1': 'R34', '2': 'R34',
          '3': 'R34', '4': 'R34', '5': 'R34', '6': 'R34', '7': 'R34', '8': 'R34', '9': 'R34', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R35', 'integer': None, 'show': 'R35',  # Row 15
          'a': 'R35', 'b': 'R35', 'r': 'R35', 's': 'R35', ';': 'R35', ':': 'R35', '(': None, ')': 'R35', ',': 'R35',
          '+': 'R35', '-': 'R35', '*': 'R35', '/': 'R35', '=': 'R35', '0': 'R35', '1': 'R35', '2': 'R35',
          '3': 'R35', '4': 'R35', '5': 'R35', '6': 'R35', '7': 'R35', '8': 'R35', '9': 'R35', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R36', 'integer': None, 'show': 'R36',  # Row 16
          'a': 'R36', 'b': 'R36', 'r': 'R36', 's': 'R36', ';': 'R36', ':': 'R36', '(': None, ')': 'R36', ',': 'R36',
          '+': 'R36', '-': 'R36', '*': 'R36', '/': 'R36', '=': 'R36', '0': 'R36', '1': 'R36', '2': 'R36',
          '3': 'R36', '4': 'R36', '5': 'R36', '6': 'R36', '7': 'R36', '8': 'R36', '9': 'R36', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R37', 'integer': None, 'show': 'R37',  # Row 17
          'a': 'R37', 'b': 'R37', 'r': 'R37', 's': 'R37', ';': 'R37', ':': 'R37', '(': None, ')': 'R37', ',': 'R37',
          '+': 'R37', '-': 'R37', '*': 'R37', '/': 'R37', '=': 'R37', '0': 'R37', '1': 'R37', '2': 'R37',
          '3': 'R37', '4': 'R37', '5': 'R37', '6': 'R37', '7': 'R37', '8': 'R37', '9': 'R37', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R38', 'integer': None, 'show': 'R38',  # Row 18
          'a': 'R38', 'b': 'R38', 'r': 'R38', 's': 'R38', ';': 'R38', ':': 'R38', '(': None, ')': 'R38', ',': 'R38',
          '+': 'R38', '-': 'R38', '*': 'R38', '/': 'R38', '=': 'R38', '0': 'R38', '1': 'R38', '2': 'R38',
          '3': 'R38', '4': 'R38', '5': 'R38', '6': 'R38', '7': 'R38', '8': 'R38', '9': 'R38', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R39', 'integer': None, 'show': 'R39',  # Row 19
          'a': 'R39', 'b': 'R39', 'r': 'R39', 's': 'R39', ';': 'R39', ':': 'R39', '(': None, ')': 'R39', ',': 'R39',
          '+': 'R39', '-': 'R39', '*': 'R39', '/': 'R39', '=': 'R39', '0': 'R39', '1': 'R39', '2': 'R39',
          '3': 'R39', '4': 'R39', '5': 'R39', '6': 'R39', '7': 'R39', '8': 'R39', '9': 'R39', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R40', 'integer': None, 'show': 'R40',  # Row 20
          'a': 'R40', 'b': 'R40', 'r': 'R40', 's': 'R40', ';': 'R40', ':': 'R40', '(': None, ')': 'R40', ',': 'R40',
          '+': 'R40', '-': 'R40', '*': 'R40', '/': 'R40', '=': 'R40', '0': 'R40', '1': 'R40', '2': 'R40',
          '3': 'R40', '4': 'R40', '5': 'R40', '6': 'R40', '7': 'R40', '8': 'R40', '9': 'R40', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R41', 'integer': None, 'show': 'R41',  # Row 21
          'a': 'R41', 'b': 'R41', 'r': 'R41', 's': 'R41', ';': 'R41', ':': 'R41', '(': None, ')': 'R41', ',': 'R41',
          '+': 'R41', '-': 'R41', '*': 'R41', '/': 'R41', '=': 'R41', '0': 'R41', '1': 'R41', '2': 'R41',
          '3': 'R41', '4': 'R41', '5': 'R41', '6': 'R41', '7': 'R41', '8': 'R41', '9': 'R41', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R42', 'integer': None, 'show': 'R42',  # Row 22
          'a': 'R42', 'b': 'R42', 'r': 'R42', 's': 'R42', ';': 'R42', ':': 'R42', '(': None, ')': 'R42', ',': 'R42',
          '+': 'R42', '-': 'R42', '*': 'R42', '/': 'R42', '=': 'R42', '0': 'R42', '1': 'R42', '2': 'R42',
          '3': 'R42', '4': 'R42', '5': 'R42', '6': 'R42', '7': 'R42', '8': 'R42', '9': 'R42', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 23
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 28, "D": 26, 'B': 27, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 24
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': 'S26    ',
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 25, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R2', 'integer': None, 'show': 'R2',  # Row 25 # Follow(R) : 'R48'
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R48', ':': 'R48', '(': None, ')': 'R48', ',': 'R48',
          '+': 'R48', '-': 'R48', '*': 'R48', '/': 'R48', '=': 'R48', '0': 'R2', '1': 'R2', '2': 'R2',
          '3': 'R2', '4': 'R2', '5': 'R2', '6': 'R2', '7': 'R2', '8': 'R2', '9': 'R2', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': 'S29', 'end': None, 'integer': None, 'show': None,  # Row 26
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 27
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': 'S30', '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 28
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': 'S31',
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': 'S36',  # Row 29
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S33', ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 37, "D": None, 'B': None, 'T': None, 'S': 32, 'C': None, 'W': 34,
          'G': None, 'A': 35, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': 'S39', 'show': None,  # Row 30
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': 38, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 31
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 28, "D": None, 'B': 40, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'S41', 'integer': None, 'show': None,  # Row 32
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R8', 'integer': None, 'show': 'S36',  # Row 33
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 37, "D": None, 'B': None, 'T': None, 'S': 43, 'C': 33, 'W': 34,
          'G': None, 'A': 35, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 38, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R10', 'integer': None, 'show': 'R10',  # Row 34
          'a': 'R10', 'b': 'R10', 'r': 'R10', 's': 'R10', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R11', 'integer': None, 'show': 'R11',  # Row 35
          'a': 'R11', 'b': 'R11', 'r': 'R11', 's': 'R11', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 36
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': 44, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 37
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': 'S45', '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 38
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S43', ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 39
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R7', ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 40
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': 'R5', '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 41
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': 'R1'},
         {'program': None, 'var': None, 'begin': None, 'end': 'R9', 'integer': None, 'show': None,  # Row 42
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': 'R4', 'end': None, 'integer': None, 'show': None,  # Row 43
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 44
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': 'S48',
          'P': None, 'I': 47, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': 46, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 45
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S54', ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 47, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': 55, 'M': 56,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 46
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 59, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 47
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': 'S60', ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 48
          'a': 'R14', 'b': 'R14', 'r': 'R14', 's': 'R14', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 49
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S77', ':': None, '(': None, ')': None, ',': None,
          '+': 'S61', '-': 'S62', '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 50
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R18', ':': None, '(': None, ')': 'R18', ',': None,
          '+': 'R18', '-': 'R18', '*': 'S63', '/': 'S64', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 51
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R21', ':': None, '(': None, ')': 'R21', ',': None,
          '+': 'R21', '-': 'R21', '*': 'R21', '/': 'R21', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 52
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R22', ':': None, '(': None, ')': 'R22', ',': None,
          '+': 'R22', '-': 'R22', '*': 'R22', '/': 'R22', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 53
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R23', ':': None, '(': None, ')': 'R23', ',': None,
          '+': 'R23', '-': 'R23', '*': 'R23', '/': 'R23', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 54
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': 'S57', '-': 'S58', '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 52, "D": None, 'B': None, 'T': None, 'S': None, 'C': 54, 'W': None,
          'G': None, 'A': None, 'E': 65, 'H': 50, 'F': 51, 'N': 53, 'K': 55, 'M': 56,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 55
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 66,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 56
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R28', ':': None, '(': None, ')': 'R28', ',': None,
          '+': 'R28', '-': 'R28', '*': 'R28', '/': 'R28', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': 67, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 57
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'R31', '1': 'R31', '2': 'R31',
          '3': 'R31', '4': 'R31', '5': 'R31', '6': 'R31', '7': 'R31', '8': 'R31', '9': 'R31', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 58
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'R32', '1': 'R32', '2': 'R32',
          '3': 'R32', '4': 'R32', '5': 'R32', '6': 'R32', '7': 'R32', '8': 'R32', '9': 'R32', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 59
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': 'S68', ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 60
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S69', ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 61
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S54', ')': None, ',': None,
          '+': 57, '-': 58, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 52, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': 70, 'F': 51, 'N': 53, 'K': 55, 'M': 56,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 62
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S54', ')': None, ',': None,
          '+': 57, '-': 58, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 52, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': 71, 'F': 51, 'N': 53, 'K': 55, 'M': 56,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 63
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S54', ')': None, ',': None,
          '+': 'S57', '-': 'S58', '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 52, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': 72, 'N': 53, 'K': 55, 'M': 56,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 64
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, '(': 'S54', ')': None, ',': None,
          '+': 'S57', '-': 'S58', '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': 52, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': 73, 'N': 53, 'K': 55, 'M': 56,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 65
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, '(': None, ')': 'S74', ',': None,
          '+': 'S61', '-': 'S62', '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 66
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R26', ':': None, '(': None, ')': 'R26', ',': None,
          '+': 'R26', '-': 'R26', '*': 'R26', '/': 'R26', '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 56,
          'L': None, 'R': None, 'X': 75, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 67
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R27', ':': None, '(': None, ')': 'R27', ',': None,
          '+': 'R27', '-': 'R27', '*': 'R27', '/': 'R27', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 68
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S72', ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R13', 'integer': None, 'show': 'R13',  # Row 69
          'a': 'R13', 'b': 'R13', 'r': 'R13', 's': 'R13', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 70
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R16', ':': None, '(': None, ')': 'R16', ',': None,
          '+': 'R16', '-': 'R16', '*': 'S63', '/': 'S64', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 71
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R17', ':': None, '(': None, ')': 'R17', ',': None,
          '+': 'R17', '-': 'R17', '*': 'S63', '/': 'S64', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 72
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R19', ':': None, '(': None, ')': 'R19', ',': None,
          '+': 'R19', '-': 'R19', '*': 'R19', '/': 'R19', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 73
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R20', ':': None, '(': None, ')': 'R20', ',': None,
          '+': 'R20', '-': 'R20', '*': 'R20', '/': 'R20', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 74
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R24', ':': None, '(': None, ')': 'R24', ',': None,
          '+': 'R24', '-': 'R24', '*': 'R24', '/': 'R24', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R12', 'integer': None, 'show': 'R12',  # Row 75
          'a': 'R12', 'b': 'R12', 'r': 'R12', 's': 'R12', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 76
          'a': None, 'b': None, 'r': None, 's': None, ';': 'R25', ':': None, '(': None, ')': 'R25', ',': None,
          '+': 'R25', '-': 'R25', '*': 'R25', '/': 'R25', '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R15', 'integer': None, 'show': 'R15',  # Row 76
          'a': 'R15', 'b': 'R15', 'r': 'R15', 's': 'R15', ';': None, ':': None, '(': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None}
         ]
