table = [{'program' : 'S2', 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : 1, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : 'ACC', 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None,  '(' : None,')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 10
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 20
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 30
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 40
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 50
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 51
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : 'R21', ':' : None, '(' : None, ')' : 'R21', ',' : None,
          '+' : 'R21', '-' : 'R21', '*' : 'R21', '/' : 'R21', '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 52
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : 'R22', ':' : None, '(' : None, ')' : 'R22', ',' : None,
          '+' : 'R22', '-' : 'R22', '*' : 'R22', '/' : 'R22', '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 53
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : 'R23', ':' : None, '(' : None, ')' : 'R23', ',' : None,
          '+' : 'R23', '-' : 'R23', '*' : 'R23', '/' : 'R23', '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 54
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : 'S57', '-' : 'S58', '*' : None, '/' : None, '=' : None, '0' : 'S13', '1' : 'S14', '2' : 'S15',
          '3' : 'S16', '4' : 'S17', '5' : 'S18', '6' : 'S19', '7' : 'S20', '8' : 'S21', '9' : 'S22', '"value=",' : None,
          'P' : None, 'I' : 52, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : 54, 'W' : None,
          'G' : None, 'A' : None, 'E' : 65, 'H' : 50, 'F' : 51, 'N' : 53, 'K' : 55, 'M' : 56,
          'L' : 4, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 55
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : 'S13', '1' : 'S14', '2' : 'S15',
          '3' : 'S16', '4' : 'S17', '5' : 'S18', '6' : 'S19', '7' : 'S20', '8' : 'S21', '9' : 'S22', '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : 66,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 56
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : 'R28', ':' : None, '(' : None, ')' : 'R28', ',' : None,
          '+' : 'R28', '-' : 'R28', '*' : 'R28', '/' : 'R28', '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : 67, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 57
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : 'R31', '1' : 'R31', '2' : 'R31',
          '3' : 'R31', '4' : 'R31', '5' : 'R31', '6' : 'R31', '7' : 'R31', '8' : 'R31', '9' : 'R31', '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 58
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : 'R32', '1' : 'R32', '2' : 'R32',
          '3' : 'R32', '4' : 'R32', '5' : 'R32', '6' : 'R32', '7' : 'R32', '8' : 'R32', '9' : 'R32', '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 59
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : 'S68', ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 60
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 70
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          {'program' : None, 'var' : None, 'begin' : None, 'end' : None, 'integer' : None, 'show' : None, # Row 0
          'a' : None, 'b' : None, 'r' : None, 's' : None, ';' : None, ':' : None, '(' : None, ')' : None, ',' : None,
          '+' : None, '-' : None, '*' : None, '/' : None, '=' : None, '0' : None, '1' : None, '2' : None,
          '3' : None, '4' : None, '5' : None, '6' : None, '7' : None, '8' : None, '9' : None, '"value=",' : None,
          'P' : None, 'I' : None, "D" : None, 'B' : None, 'T' : None, 'S' : None, 'C' : None, 'W' : None,
          'G' : None, 'A' : None, 'E' : None, 'H' : None, 'F' : None, 'N' : None, 'K' : None, 'M' : None,
          'L' : None, 'R' : None, 'X' : None, '$' : None},
          ]