table = [{'program': 'S2', 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': 1, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'ACC', 'integer': None, 'show': None,  # Row 1
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': 'S3', 'show': None,  # Row 2
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 3
          'a': None, 'b': None, 'r': None, 's': None, ';': 'S9', ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 4
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 10, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R5', 'integer': None, 'show': 'R5',  # Row 5
          'a': 'R5', 'b': 'R5', 'r': 'R5', 's': 'R5', ';': 'R5', ':': 'R5', ')': 'R5', ',': 'R5',
          '+': 'R5', '-': 'R5', '*': 'R5', '/': 'R5', '=': 'R5', '0': 'R5', '1': 'R5', '2': 'R5',
          '3': 'R5', '4': 'R5', '5': 'R5', '6': 'R5', '7': 'R5', '8': 'R5', '9': 'R5', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R6', 'integer': None, 'show': 'R6',  # Row 6
          'a': 'R6', 'b': 'R6', 'r': 'R6', 's': 'R6', ';': 'R6', ':': 'R6', ')': 'R6', ',': 'R6',
          '+': 'R6', '-': 'R6', '*': 'R6', '/': 'R6', '=': 'R6', '0': 'R6', '1': 'R6', '2': 'R6',
          '3': 'R6', '4': 'R6', '5': 'R6', '6': 'R6', '7': 'R6', '8': 'R6', '9': 'R6', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R7', 'integer': None, 'show': 'R7',  # Row 7
          'a': 'R7', 'b': 'R7', 'r': 'R7', 's': 'R7', ';': 'R7', ':': 'R7', ')': 'R7', ',': 'R7',
          '+': 'R7', '-': 'R7', '*': 'R7', '/': 'R7', '=': 'R7', '0': 'R7', '1': 'R7', '2': 'R7',
          '3': 'R7', '4': 'R7', '5': 'R7', '6': 'R7', '7': 'R7', '8': 'R7', '9': 'R7', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R8', 'integer': None, 'show': 'R8',  # Row 8
          'a': 'R8', 'b': 'R8', 'r': 'R8', 's': 'R8', ';': 'R8', ':': 'R8', ')': 'R8', ',': 'R8',
          '+': 'R8', '-': 'R8', '*': 'R8', '/': 'R8', '=': 'R8', '0': 'R8', '1': 'R8', '2': 'R8',
          '3': 'R8', '4': 'R8', '5': 'R8', '6': 'R8', '7': 'R8', '8': 'R8', '9': 'R8', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': 'S23', 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 9
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R10', 'integer': None, 'show': 'R10',  # Row 10
          'a': 'R10', 'b': 'R10', 'r': 'R10', 's': 'R10', ';': 'R10', ':': 'R10', ')': 'R10', ',': 'R10',
          '+': 'R10', '-': 'R10', '*': 'R10', '/': 'R10', '=': 'R10', '0': 'R10', '1': 'R10', '2': 'R10',
          '3': 'R10', '4': 'R10', '5': 'R10', '6': 'R10', '7': 'R10', '8': 'R10', '9': 'R10', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 11
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 24, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 12
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': 'S13', '1': 'S14', '2': 'S15',
          '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': 12,
          'L': 11, 'R': 25, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R33', 'integer': None, 'show': 'R33',  # Row 13
          'a': 'R33', 'b': 'R33', 'r': 'R33', 's': 'R33', ';': 'R33', ':': 'R33', ')': 'R33', ',': 'R33',
          '+': 'R33', '-': 'R33', '*': 'R33', '/': 'R33', '=': 'R33', '0': 'R33', '1': 'R33', '2': 'R33',
          '3': 'R33', '4': 'R33', '5': 'R33', '6': 'R33', '7': 'R33', '8': 'R33', '9': 'R33', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R34', 'integer': None, 'show': 'R34',  # Row 14
          'a': 'R34', 'b': 'R34', 'r': 'R34', 's': 'R34', ';': 'R34', ':': 'R34', ')': 'R34', ',': 'R34',
          '+': 'R34', '-': 'R34', '*': 'R34', '/': 'R34', '=': 'R34', '0': 'R34', '1': 'R34', '2': 'R34',
          '3': 'R34', '4': 'R34', '5': 'R34', '6': 'R34', '7': 'R34', '8': 'R34', '9': 'R34', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R35', 'integer': None, 'show': 'R35',  # Row 15
          'a': 'R35', 'b': 'R35', 'r': 'R35', 's': 'R35', ';': 'R35', ':': 'R35', ')': 'R35', ',': 'R35',
          '+': 'R35', '-': 'R35', '*': 'R35', '/': 'R35', '=': 'R35', '0': 'R35', '1': 'R35', '2': 'R35',
          '3': 'R35', '4': 'R35', '5': 'R35', '6': 'R35', '7': 'R35', '8': 'R35', '9': 'R35', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R36', 'integer': None, 'show': 'R36',  # Row 16
          'a': 'R36', 'b': 'R36', 'r': 'R36', 's': 'R36', ';': 'R36', ':': 'R36', ')': 'R36', ',': 'R36',
          '+': 'R36', '-': 'R36', '*': 'R36', '/': 'R36', '=': 'R36', '0': 'R36', '1': 'R36', '2': 'R36',
          '3': 'R36', '4': 'R36', '5': 'R36', '6': 'R36', '7': 'R36', '8': 'R36', '9': 'R36', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R37', 'integer': None, 'show': 'R37',  # Row 17
          'a': 'R37', 'b': 'R37', 'r': 'R37', 's': 'R37', ';': 'R37', ':': 'R37', ')': 'R37', ',': 'R37',
          '+': 'R37', '-': 'R37', '*': 'R37', '/': 'R37', '=': 'R37', '0': 'R37', '1': 'R37', '2': 'R37',
          '3': 'R37', '4': 'R37', '5': 'R37', '6': 'R37', '7': 'R37', '8': 'R37', '9': 'R37', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R38', 'integer': None, 'show': 'R38',  # Row 18
          'a': 'R38', 'b': 'R38', 'r': 'R38', 's': 'R38', ';': 'R38', ':': 'R38', ')': 'R38', ',': 'R38',
          '+': 'R38', '-': 'R38', '*': 'R38', '/': 'R38', '=': 'R38', '0': 'R38', '1': 'R38', '2': 'R38',
          '3': 'R38', '4': 'R38', '5': 'R38', '6': 'R38', '7': 'R38', '8': 'R38', '9': 'R38', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R39', 'integer': None, 'show': 'R39',  # Row 19
          'a': 'R39', 'b': 'R39', 'r': 'R39', 's': 'R39', ';': 'R39', ':': 'R39', ')': 'R39', ',': 'R39',
          '+': 'R39', '-': 'R39', '*': 'R39', '/': 'R39', '=': 'R39', '0': 'R39', '1': 'R39', '2': 'R39',
          '3': 'R39', '4': 'R39', '5': 'R39', '6': 'R39', '7': 'R39', '8': 'R39', '9': 'R39', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R40', 'integer': None, 'show': 'R40',  # Row 20
          'a': 'R40', 'b': 'R40', 'r': 'R40', 's': 'R40', ';': 'R40', ':': 'R40', ')': 'R40', ',': 'R40',
          '+': 'R40', '-': 'R40', '*': 'R40', '/': 'R40', '=': 'R40', '0': 'R40', '1': 'R40', '2': 'R40',
          '3': 'R40', '4': 'R40', '5': 'R40', '6': 'R40', '7': 'R40', '8': 'R40', '9': 'R40', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R41', 'integer': None, 'show': 'R41',  # Row 21
          'a': 'R41', 'b': 'R41', 'r': 'R41', 's': 'R41', ';': 'R41', ':': 'R41', ')': 'R41', ',': 'R41',
          '+': 'R41', '-': 'R41', '*': 'R41', '/': 'R41', '=': 'R41', '0': 'R41', '1': 'R41', '2': 'R41',
          '3': 'R41', '4': 'R41', '5': 'R41', '6': 'R41', '7': 'R41', '8': 'R41', '9': 'R41', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R42', 'integer': None, 'show': 'R42',  # Row 22
          'a': 'R42', 'b': 'R42', 'r': 'R42', 's': 'R42', ';': 'R42', ':': 'R42', ')': 'R42', ',': 'R42',
          '+': 'R42', '-': 'R42', '*': 'R42', '/': 'R42', '=': 'R42', '0': 'R42', '1': 'R42', '2': 'R42',
          '3': 'R42', '4': 'R42', '5': 'R42', '6': 'R42', '7': 'R42', '8': 'R42', '9': 'R42', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 23
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': 28, "D": 26, 'B': 27, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 4, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 24
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': 'S26    ',
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': 25, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': 'R2', 'integer': None, 'show': 'R2',  # Row 25
          'a': 'R2', 'b': 'R2', 'r': 'R2', 's': 'R2', ';': 'R2', ':': 'R2', ')': 'R2', ',': 'R2',
          '+': 'R2', '-': 'R2', '*': 'R2', '/': 'R2', '=': 'R2', '0': 'R2', '1': 'R2', '2': 'R2',
          '3': 'R2', '4': 'R2', '5': 'R2', '6': 'R2', '7': 'R2', '8': 'R2', '9': 'R2', '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': 'S29', 'end': None, 'integer': None, 'show': None,  # Row 26
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {':': 'S30'},  # 27
         {',': 'S31'},  # 28
         {'S': 32, '(': 'S33', 'W': 34, 'A': 35, 'show': 'S36', 'I': 37,
         'L': 4, 'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8'},  # 29
         {'T': 38, 'integer': 'S39'},  # 30
         {'B': 40, 'I': 28, 'L': 4, 'a': 'S5',
          'b': 'S6', 'r': 'S7', 's': 'S8'},  # 31
         {'end': 'S41'},  # 32
         {'s': '43', 'C': '33', 'W': 34, 'A': 35, 'show': 'S36', 'I': 37, 'L': 38,
          # 33 [33, Follow (S)] = 'R8'
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', 'end': 'R8'},
         {'show': 'R10', 'a': 'R10', 'b': 'R10', 'r': 'R10',
          's': 'R10', 'end': 'R10'},  # 34 Follow(C) : 'R10'
         {'show': 'R11', 'a': 'R11', 'b': 'R11', 'r': 'R11',
          's': 'R11', 'end': 'R11'},  # 35 Follow(C) : 'R11'
         {'C': 44},  # 36
         {'=': 'S45'},  # 37
         {';': 'S43'},  # 38
         {';': 'R7'},  # 39 Follow(T) : 'R7'
         {':': 'R5'},  # 40 Follow(B) : 'R5'
         {'P': 'R1'},  # 41 Follow(P) : R1 or 'Acc'
         {'end': 'R9'},  # 42 Follow(S) : 'R9'
         {'begin': 'R4'},  # 43 Follow(D) : 'R4'
         {'G': 46, 'I': 47, '"value=",': 'S48', 'L': 4,
          'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8'},  # 44
         {'(': 'S54', 'I': 47, 'K': 55, 'M': 56, '0': 'S13', '1': 'S14', '2': 'S15', '3': 'S16', '4': 'S17',
         '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22', 'a': 'S5', 'b': 'S6', 'r': 'S7', 's': 'S8', },  # 45
         {'I': 59, 'L': 4, 'a': 'S5', 'b': 'S6',
          'r': 'S7', 's': 'S8'},  # 46 possibly I : 59
         {')': 'S60'},  # 47 Might be S60? hard to read
         {'a': 'R14', 'b': 'R14', 'r': 'R14',
          's': 'R14', },  # 48 Follow(G) : 'R14'
         # 49 Follow (A) : 'R19' ';' goes to new state
         {'+': 'S61', '-': 'S62', ';': 'S77'},
         {'*': 'S63', '/': 'S64', ';': 'R18', '+': 'R18',
          '-': 'R18', ')': 'R18'},  # 50 Follow(E) : 'R18'
         {';': 'R21', '+': 'R21', '-': 'R21',
          ')': 'R21'},  # 51 Follow(H) : 'R21'
         {';': 'R22', '+': 'R22', '-': 'R22', ')': 'R22',
          '*': 'R22', '*': 'R22'},  # 52 Follow(F) -> I : 'R22"
         {';': 'R23', '+': 'R23', '-': 'R23', ')': 'R23',
          '*': 'R23', '*': 'R23'},  # 53 Follow(F) : 'R23'
         {'E': 65, 'H': 50, 'F': 51, 'I': 52, 'N': 51, '(': 'S54', 'L': 4, 'K': 55, 'M': 56, '+': 'S57', '-': 'S58',
         '0': 'S13', '1': 'S14', '2': 'S15', '3': 'S16', '4': 'S17', '5': 'S18', '6': 'S19', '7': 'S20', '8': 'S21', '9': 'S22'},  # 54
         {'M': 66},  # 55
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 30
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 40
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 50
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 60
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 70
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         {'program': None, 'var': None, 'begin': None, 'end': None, 'integer': None, 'show': None,  # Row 0
          'a': None, 'b': None, 'r': None, 's': None, ';': None, ':': None, ')': None, ',': None,
          '+': None, '-': None, '*': None, '/': None, '=': None, '0': None, '1': None, '2': None,
          '3': None, '4': None, '5': None, '6': None, '7': None, '8': None, '9': None, '"value=",': None,
          'P': None, 'I': None, "D": None, 'B': None, 'T': None, 'S': None, 'C': None, 'W': None,
          'G': None, 'A': None, 'E': None, 'H': None, 'F': None, 'N': None, 'K': None, 'M': None,
          'L': None, 'R': None, 'X': None, '$': None},
         ]
